project:
  type: website
  execute-dir: file
  resources:
    - CNAME
    - audio
    - video
    
website:
  title: "Blog"
  site-url: https://blog.benjaminhlina.com  
  reader-mode: true
  google-analytics: "G-MGFSRVFVLF"
  navbar:
    background: "#28535c"
    right:
      - about.qmd  
      - icon: wordpress
        href: https://benjaminhlina.com
      - icon: github
        href: https://github.com/benjaminhlina
      - text: "{{< iconify simple-icons bluesky >}}"
        href: https://bsky.app/profile/benjaminhlina.bsky.social
      - icon: mortarboard
        href: https://scholar.google.com/citations?user=upRdN9AAAAAJ&hl=en 
      - text: R-bloggers
        href: https://www.r-bloggers.com
      - icon: rss
        href: index.xml
        
  
    
  
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-title: "Contents"
    number-sections: true
    toc-expand: true
    number-offset: 1
    number-depth: 4
    # link-external-icon: true
    # link-external-newwindow: true
execute:
  freeze: auto

