project:
  type: website
  execute-dir: file
  resources:
    - CNAME
    - audio
    - video
    - frm/plans
    - frm/reports
    
website:
  title: "Blog"
  navbar:
    background: "#28535c"
    right:
      - about.qmd
      - icon: github
        href: https://github.com/benjaminhlina
      - icon: twitter
        href: https://twitter.com/ben_hlina
      - icon: wordpress
        href: https://benjaminhlina.com
  
format:
  html:
    theme: cosmo
    css: styles.css
execute:
  freeze: auto
editor: visual

