project:
  type: website
  execute-dir: file
  resources:
    - CNAME
    - audio
    - video
    
website:
  title: "Blog"
  google-analytics: "G-MGFSRVFVLF"
  navbar:
    background: "#28535c"
    right:
      - about.qmd  
      - icon: wordpress
        href: https://benjaminhlina.com
      - icon: github
        href: https://github.com/benjaminhlina
      - icon: twitter
        href: https://twitter.com/ben_hlina
      - icon: mortarboard
        href: https://scholar.google.com/citations?user=upRdN9AAAAAJ&hl=en 
    
  
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-title: "Contents"
    number-sections: true
    toc-expand: true
    number-offset: 1
    number-depth: 4
    # link-external-icon: true
    # link-external-newwindow: true
execute:
  freeze: auto

