project:
  type: website
  execute-dir: file
  resources:
    - CNAME
    - audio
    - video
    
website:
  title: "Blog"
  navbar:
    background: "#28535c"
    right:
      - about.qmd  
      - icon: wordpress
        href: https://benjaminhlina.com
      - icon: github
        href: https://github.com/benjaminhlina
      - icon: twitter
        href: https://twitter.com/ben_hlina
    
  
format:
  html:
    theme: cosmo
    css: styles.css
    # toc: true
    # link-external-icon: true
    # link-external-newwindow: true
website:
  google-analytics: "G-MGFSRVFVLF"

execute:
  freeze: auto

